source :rubygems

gem "eventmachine"
gem "em-http-request"
gem "nats"
gem "ruby-hmac"
gem "uuidtools"
gem "sinatra"
gem "thin"
gem "dalli"
gem "datamapper", ">= 0.10.2"
gem "dm-sqlite-adapter"

gem 'vcap_common', '>= 1.0.8', :require => ['vcap/common', 'vcap/component']
gem 'vcap_logging', '>=1.0.0', :require => ['vcap/logging']
gem 'vcap_services_base'

group :test do
  gem "rake"
  gem "rspec"
  gem "rcov", '< 1.0.0'
  gem "ci_reporter"
end
